set_property PACKAGE_PIN V12 [get_ports Pmod_out_0_pin1_io]
set_property PACKAGE_PIN W16 [get_ports Pmod_out_0_pin2_io]
set_property PACKAGE_PIN J15 [get_ports Pmod_out_0_pin3_io]
set_property PACKAGE_PIN H15 [get_ports Pmod_out_0_pin4_io]
set_property PACKAGE_PIN V13 [get_ports Pmod_out_0_pin7_io]
set_property PACKAGE_PIN U17 [get_ports Pmod_out_0_pin8_io]
set_property PACKAGE_PIN T17 [get_ports Pmod_out_0_pin9_io]
set_property PACKAGE_PIN Y17 [get_ports Pmod_out_0_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin10_io]

set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_sda_io]

set_property PULLUP true [get_ports iic_rtl_scl_io]
set_property PULLUP true [get_ports iic_rtl_sda_io]
set_property PACKAGE_PIN T14 [get_ports iic_rtl_sda_io]
set_property PACKAGE_PIN T15 [get_ports iic_rtl_scl_io]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_baudoutn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ctsn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dcdn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ddis]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dsrn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dtrn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_out1n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_out2n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ri]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rtsn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxrdyn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txrdyn]

set_property PACKAGE_PIN T14 [get_ports IIC_0_sda_io]
set_property PACKAGE_PIN T15 [get_ports IIC_0_scl_io]
set_property PULLUP true [get_ports IIC_0_scl_io]
set_property PULLUP true [get_ports IIC_0_sda_io]
