# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_xbar_0/Final_Project_BD_xbar_0.xci
# IP: The module: 'Final_Project_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_xbar_0/Final_Project_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_xbar_0/Final_Project_BD_xbar_0.xci
# IP: The module: 'Final_Project_BD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_xbar_0/Final_Project_BD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
