# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo.xdc

# Block Designs: bd/Final_Project_BD/Final_Project_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD || ORIG_REF_NAME==Final_Project_BD} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_processing_system7_0_0/Final_Project_BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_processing_system7_0_0 || ORIG_REF_NAME==Final_Project_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/Final_Project_BD_PmodCOLOR_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_PmodCOLOR_0_2 || ORIG_REF_NAME==Final_Project_BD_PmodCOLOR_0_2} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_xbar_0/Final_Project_BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_xbar_0 || ORIG_REF_NAME==Final_Project_BD_xbar_0} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_ps7_0_axi_periph_2/Final_Project_BD_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_ps7_0_axi_periph_2 || ORIG_REF_NAME==Final_Project_BD_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_rst_ps7_0_50M_2 || ORIG_REF_NAME==Final_Project_BD_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_auto_pc_0/Final_Project_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_auto_pc_0 || ORIG_REF_NAME==Final_Project_BD_auto_pc_0} -quiet] -quiet

# IP: bd/Final_Project_BD/ip/Final_Project_BD_axi_iic_0_0/Final_Project_BD_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_BD_axi_iic_0_0 || ORIG_REF_NAME==Final_Project_BD_axi_iic_0_0} -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/Final_Project_BD_ooc.xdc
