# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2.xci
# IP: The module: 'Final_Project_BD_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2.xci
# IP: The module: 'Final_Project_BD_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_rst_ps7_0_50M_2/Final_Project_BD_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
