# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/Final_Project_BD_PmodCOLOR_0_2.xci
# IP: The module: 'Final_Project_BD_PmodCOLOR_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_0/PmodCOLOR_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_0 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_1/PmodCOLOR_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_1 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_1} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_2/PmodCOLOR_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_2 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_2} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlconcat_0_0/PmodCOLOR_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_0 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlconcat_0_1/PmodCOLOR_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_1 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_1} -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_ooc.xdc

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/Final_Project_BD_PmodCOLOR_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_PmodCOLOR_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_PmodCOLOR_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_ooc.xdc

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/Final_Project_BD_PmodCOLOR_0_2.xci
# IP: The module: 'Final_Project_BD_PmodCOLOR_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_0/PmodCOLOR_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_0 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_1/PmodCOLOR_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_1 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_1} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlslice_0_2/PmodCOLOR_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlslice_0_2 || ORIG_REF_NAME==PmodCOLOR_xlslice_0_2} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlconcat_0_0/PmodCOLOR_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_0 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_0} -quiet] -quiet

# IP: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_xlconcat_0_1/PmodCOLOR_xlconcat_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCOLOR_xlconcat_0_1 || ORIG_REF_NAME==PmodCOLOR_xlconcat_0_1} -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_iic_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_iic_0_0/PmodCOLOR_axi_iic_0_0_ooc.xdc

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/Final_Project_BD_PmodCOLOR_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_PmodCOLOR_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_BD_PmodCOLOR_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0_ooc.xdc

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_axi_gpio_0_0/PmodCOLOR_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_axi_gpio_0_0 || ORIG_REF_NAME==PmodCOLOR_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/PmodCOLOR_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCOLOR_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCOLOR_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/rgalmazar/Documents/ECE520/FinalProject/520-Final-Project/hardware/Final_Project/Final_Project.gen/sources_1/bd/Final_Project_BD/ip/Final_Project_BD_PmodCOLOR_0_2/src/PmodCOLOR_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
